// <auto-generated />
using System;
using InvestimentApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestimentApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240907160145_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvestimentApi.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(16,12)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("InvestimentApi.Models.OrderBookItem", b =>
                {
                    b.Property<int>("OrderBookItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderBookItemId"));

                    b.Property<Guid>("OrderCalculationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(16,12)");

                    b.HasKey("OrderBookItemId");

                    b.HasIndex("OrderCalculationId");

                    b.ToTable("OrderBookItems");
                });

            modelBuilder.Entity("OrderCalculation", b =>
                {
                    b.Property<Guid>("OrderCalculationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(15,5)");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("decimal(20,15)");

                    b.HasKey("OrderCalculationId");

                    b.ToTable("OrderCalculations");
                });

            modelBuilder.Entity("InvestimentApi.Models.OrderBookItem", b =>
                {
                    b.HasOne("OrderCalculation", null)
                        .WithMany("UsedOrders")
                        .HasForeignKey("OrderCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderCalculation", b =>
                {
                    b.Navigation("UsedOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
